# Check out https://docs.codemagic.io/yaml/building-a-native-ios-app/ for more information
# Please review and update values in curly braces

workflows:
    ios-app:
        name: iOS App
        environment:
            vars:
                TESTFLIGHT_INDEX_DIFF: 23
                XCODE_PROJECT: "swiftly"
                XCODE_SCHEME: "swiftly"
                CM_CERTIFICATE: Encrypted(...)
                CM_CERTIFICATE_PASSWORD: Encrypted(..)
                CM_PROVISIONING_PROFILE: Encrypted(...)
            xcode: latest
            cocoapods: default
        triggering:
          events:
              - push
              - tag
          branch_patterns:
              - pattern: master
                include: true
                source: true
        scripts:
            - keychain initialize
            - |
              # set up provisioning profiles
              PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
              mkdir -p "$PROFILES_HOME"
              PROFILE_PATH="$(mktemp "$PROFILES_HOME"/$(uuidgen).mobileprovision)"
              echo ${CM_PROVISIONING_PROFILE} | base64 --decode > $PROFILE_PATH
              echo "Saved provisioning profile $PROFILE_PATH"
            - |
              # set up signing certificate
              echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
              keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $CM_CERTIFICATE_PASSWORD
            - |
              # increment build number
              #!/bin/sh
              set -e
              set -x
              cd $FCI_BUILD_DIR
              agvtool new-version -all $(($BUILD_NUMBER + $TESTFLIGHT_INDEX_DIFF +1))
            - xcode-project use-profiles
            - xcode-project build-ipa --project "$XCODE_PROJECT.xcodeproj" --scheme "$XCODE_SCHEME"
        artifacts:
            - build/ios/ipa/*.ipa
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        publishing:
          app_store_connect:                 
              apple_id: YOUR_APPLE_ID  
              password: Encrypted(...)